<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Build" Version="18.8.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="NWebsec.AspNetCore.Middleware" Version="3.0.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.29.0.143774" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <!-- Pin Nuget package versions to fix NU1901. Might not be needed if Microsoft.VisualStudio.Web.CodeGenerators.Mvc is updated -->
    <PackageVersion Include="Nuget.Packaging" Version="7.6.0" />
    <PackageVersion Include="Nuget.ProjectModel" Version="7.6.0" />
    <PackageVersion Include="Nuget.Protocol" Version="7.6.0" />
  </ItemGroup>
</Project>